query userProduct($id: String!) {
  userProduct(id: $id) {
    avatar {
      fullOriginalUrl
      fullThumbUrl
      id
    }
    avatarId
    createdAt
    deletedAt
    descriptionImageIds
    descriptionImages {
      fullOriginalUrl
      fullThumbUrl
      id
      type
    }
    detail
    id
    isActive
    isFavorite
    isFixedCost
    isNew
    manufacturer {
      id
      isActive
      name
      type
    }
    model {
      id
      isActive
      name
      type
    }
    name
    numberOrder
    numberSold
    operatingNumber
    operatingUnit
    ordinalNumber
    origin {
      id
      isActive
      name
      type
    }
    partNumber
    partOfProduct {
      id
      isActive
      name
      type
    }
    partnerId
    productType {
      id
      isActive
      name
      type
    }
    productUnit {
      id
      isActive
      name
      type
    }
    quantity
    reviewSummary {
      percent
      starAverage
      total
    }
    serialNumber
    star
    starInfo {
      star
      total
    }
    type
    unitPrice
    updatedAt
    vehicleRegistrationPlate
    vinNumber
    yearOfManufacture
  }
}
